# Задаём имя workflow
name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps: 
      - name: List files and copy repository
      # Выводим список файлов в рабочей директории до клонирования репозитория
        run: |
          ls -a
      # Экшен, который клонирует репозиторий в рабочую директорию
      #- uses: actions/checkout@v4
      # ---------------------------------------
      # GIT команды, которые клонируют репозиторий в рабочую директорию
      - name: Copy files
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      # Конец списка команд
      # Выводим список файлов в рабочей директории после клонирования репозитория
      - name: List files
        run: ls -a